import { chromium } from '@playwright/test';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, resolve } from 'node:path';
const types={'.js':'text/javascript','.css':'text/css','.html':'text/html','.wasm':'application/wasm','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};
const server=createServer(async(req,res)=>{try {const pathname=decodeURIComponent(req.url.split('?')[0]).replace(/^\/videocompressor(?=\/)/,'');const path=resolve('dist','.'+(pathname==='/'?'/index.html':pathname));if(!path.startsWith(resolve('dist')+'\\'))throw Error();res.setHeader('Content-Type',types[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.statusCode=404;res.end();}}).listen(4173,'127.0.0.1');
const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
try{
const page=await browser.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('error',e.message)});page.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url())});await page.goto(process.env.SMOKE_URL || 'http://127.0.0.1:4173/videocompressor/');
const sample=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=320;canvas.height=240;const ctx=canvas.getContext('2d');const stream=canvas.captureStream(60);const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8',videoBitsPerSecond:1500000});const parts=[];recorder.ondataavailable=e=>parts.push(e.data);const done=new Promise(r=>recorder.onstop=r);recorder.start();let n=0;const timer=setInterval(()=>{ctx.fillStyle=`hsl(${n++*20},70%,50%)`;ctx.fillRect(0,0,320,240);ctx.fillStyle='white';ctx.fillRect((n*10)%300,80,20,80);},16);await new Promise(r=>setTimeout(r,2000));clearInterval(timer);recorder.stop();await done;stream.getTracks().forEach(t=>t.stop());return Array.from(new Uint8Array(await new Blob(parts).arrayBuffer()));});
await page.locator('#file').setInputFiles({name:'sample.webm',mimeType:'video/webm',buffer:Buffer.from(sample)});
await page.locator('#start').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('start').disabled,{},{timeout:90000});
console.log('metadata:',await page.locator('#metadata').textContent());await page.locator('#target').fill('0.1');await page.locator('#start').click();await page.locator('#result').waitFor({state:'visible',timeout:120000});
const result=await page.evaluate(async()=>{const b=await(await fetch(document.getElementById('download').href)).blob();return {bytes:b.size,stats:document.getElementById('stats').textContent};});if(result.bytes>=100000)throw Error('Target exceeded');console.log('result:',result);
await page.locator('#start').click();await page.waitForTimeout(150);await page.locator('#cancel').click();await page.waitForFunction(()=>document.getElementById('progress-panel').hidden);console.log('cancel:',await page.locator('#message').textContent());
await page.locator('#file').setInputFiles({name:'sample.webm',mimeType:'video/webm',buffer:Buffer.from(sample)});await page.waitForFunction(()=>!document.getElementById('start').disabled,{},{timeout:90000});await page.locator('#start').click();await page.locator('#result').waitFor({state:'visible',timeout:120000});console.log('restart passed');
const audioSample=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=240;c.getContext('2d').fillRect(0,0,320,240);const stream=c.captureStream(30);const context=new AudioContext();await context.resume();const oscillator=context.createOscillator();const destination=context.createMediaStreamDestination();oscillator.connect(destination);oscillator.start();stream.addTrack(destination.stream.getAudioTracks()[0]);const recorder=new MediaRecorder(stream,{mimeType:'video/webm;codecs=vp8,opus'});const parts=[];recorder.ondataavailable=e=>parts.push(e.data);const done=new Promise(r=>recorder.onstop=r);recorder.start();await new Promise(r=>setTimeout(r,1500));recorder.stop();await done;oscillator.stop();stream.getTracks().forEach(t=>t.stop());await context.close();return Array.from(new Uint8Array(await new Blob(parts).arrayBuffer()));});
await page.locator('#file').setInputFiles({name:'audio.webm',mimeType:'video/webm',buffer:Buffer.from(audioSample)});await page.waitForFunction(()=>!document.getElementById('start').disabled,{},{timeout:90000});if(!(await page.locator('#metadata').textContent()).includes('음성 있음'))throw Error('Audio not detected');await page.locator('#start').click();await page.locator('#result').waitFor({state:'visible',timeout:120000});await page.waitForFunction(()=>document.getElementById('output').readyState>=1);console.log('AAC audio encode passed');
await page.setViewportSize({width:320,height:800});await page.screenshot({path:'tests/mobile.png',fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
await page.waitForFunction(async()=>!!navigator.serviceWorker.controller,{},{timeout:60000});await page.waitForTimeout(1000);await page.context().setOffline(true);await page.reload();await page.locator('h1').waitFor();console.log('offline shell passed');await page.locator('#file').setInputFiles({name:'offline.webm',mimeType:'video/webm',buffer:Buffer.from(sample)});await page.waitForFunction(()=>!document.getElementById('start').disabled,{},{timeout:90000});await page.locator('#target').fill('0.1');await page.locator('#start').click();await page.locator('#result').waitFor({state:'visible',timeout:120000});await page.waitForFunction(()=>document.getElementById('output').readyState>=1);console.log('offline encode and MP4 playback metadata passed');console.log('page errors:',errors);if(errors.length)throw Error(errors.join('\n'));
}finally{await browser.close();server.close();}
