export const layout = `
<header><a class="brand" href="./"><span class="logo">▶</span> FRAMEFIT <small>VIDEO COMPRESSOR</small></a><span class="local">● 내 기기에서 안전하게</span></header>
<section class="intro"><span class="eyebrow">작게 담아, 가볍게 보내세요</span><h1>프레임핏 영상 압축기</h1><p>원하는 용량에 맞춰, <em>간편하게.</em></p></section>
<div class="workspace"><section class="card source"><div class="section-title"><span>01</span><h2>영상 선택</h2></div><label id="drop" class="drop" tabindex="0"><span class="upload-icon">↥</span><strong>영상을 여기에 놓아주세요</strong><span>또는 눌러서 파일 선택</span><small>MP4 · MOV · WEBM · MKV 등 / 코덱에 따라 지원 여부가 달라집니다</small><input id="file" type="file" accept="video/*,.mkv,.avi" hidden></label><video id="preview" controls playsinline hidden></video><p id="metadata" class="muted">원본 영상은 서버로 전송되지 않습니다.</p></section>
<section class="card settings"><div class="section-title"><span>02</span><h2>압축 설정</h2></div><fieldset id="settings"><legend class="sr-only">압축 설정</legend><label for="target">목표 용량 <small>1MB = 1,000,000바이트</small></label><div class="number"><input id="target" type="number" min="0.01" max="2000" step="0.01" value="10"><span>MB 미만</span></div><details open><summary>고급 설정</summary><label class="check"><input id="audio" type="checkbox" checked> 음성 유지</label><label class="check"><input id="audio-quality" type="checkbox" checked> 음질 유지하기</label><p class="muted">원본 AAC는 그대로 유지합니다. 다른 형식은 고음질 AAC로 변환하며, 무손실을 보장하지 않습니다.</p><label for="fps">최대 FPS</label><input id="fps" class="advanced-number" type="number" min="1" max="120" step="1" value="30"><p class="muted">원본 FPS보다 높이지 않습니다. FPS를 높이면 압축 시간이 늘어납니다.</p><label class="check"><input id="resolution" type="checkbox"> 원본 해상도 유지</label></details></fieldset><button id="start" class="primary" disabled>영상 압축하기 <span>→</span></button><p class="hint">원본과 동일한 화질을 보장하지 않습니다.</p></section></div>
<section id="progress-panel" class="card" hidden><div class="section-title"><h2 id="stage">준비 중</h2><span id="elapsed">0초</span></div><progress id="progress" max="100"></progress><p id="percent" class="muted"></p><p class="muted">압축하는 동안 화면을 켜 두고 이 탭을 유지하세요.</p><button id="cancel">취소</button></section>
<p id="message" role="status" aria-live="polite"></p>
<section id="result" class="card" hidden><div class="section-title"><span>✓</span><h2>압축 완료</h2></div><div id="stats" class="stats"></div><video id="output" controls playsinline></video><div class="actions"><a id="download" class="primary">MP4 다운로드 ↓</a><button id="share" hidden>공유하기</button><button id="reset">새 영상 압축하기</button></div></section>
<footer><p>파일은 내 기기에서만 처리됩니다. 가입 없이, 업로드 없이.</p><p id="environment"></p><button id="install" hidden>앱 설치</button><span id="offline">오프라인 준비 상태 확인 중…</span></footer>`;
export const mb = bytes => (bytes / 1000000).toLocaleString('ko-KR', { maximumFractionDigits: 2 }) + 'MB';
